### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by newfinal100** [EgorOrachyov/Berserk#5]
Hey! I was looking through your project and I liked it so much I wanted to contribute to it by designing a logo. I made a few variations of what I had in mind, and if you'd want to have this logo I can make any improvements/adjustments you may need. Please don't feel obliged to accept this though :) Only if you really like the concept and the design. Looking forward to hearing from you!

![berserk](https://user-images.githubusercontent.com/49202520/55676325-648fcc00-58d3-11e9-9181-de8a95639eef.jpg)

**Comment by EgorOrachyov** [comment]
Hello! Thank you so much for your interest to the project. Logo concepts created by you are wonderful. The following one [pic.1] will suit the project idea and will look awesome! However, if it is not a secrete, could you tell me, what this geometry puzzle means [pic.2] :) 
<img width="246" alt="concept" src="https://user-images.githubusercontent.com/31863304/55680538-74cf9780-5923-11e9-96c0-98f3306007bf.png">  
<img width="90" alt="puzzle" src="https://user-images.githubusercontent.com/31863304/55680557-ce37c680-5923-11e9-9db0-393570eca0c8.png">

**Comment by newfinal100** [comment]
Well, since your project is about "tools for creating real-time graphics applications with basic physical and audio functions", I wanted to create something that symbolizes this tool in order for it to look like it's building or developing something. So I tried a few things and didn't like them, then I figured maybe a game handle that looks like it's still building/developing might be a good idea and created this geometry puzzle :) What do you think?

**Comment by EgorOrachyov** [comment]
Yeah, in this case this concept feels clear. Visualization of building/developing something from set of smaller building blocks. Only one thing, could you redesign logo in way building blocks puzzle fits written engine name in terms of proportions. I mean, there is need of little movements and maybe scale operations in order to balance text (make font more solid, for example, without style changement) and icon. So, how about that ?)

And how do you want me to include you in collaborators list. I mean: GitHub nickname, maybe something else?

Logo:
<img width="246" alt="concept" src="https://user-images.githubusercontent.com/31863304/55684630-0f48ce80-5956-11e9-9453-254bba4547f2.png">

**Comment by newfinal100** [comment]
Hmm you mean like this?

![berserk 2-01](https://user-images.githubusercontent.com/49202520/55684707-af025e80-594e-11e9-9e04-8eb4e4901215.jpg)

And about the collaborators list, whichever way you'd want is okay :)

**Comment by newfinal100** [comment]
I made both of them a little bit more solid but the one below is slightly more solid than the one above, you choose which one you like more and if this is what you meant :))

**Comment by EgorOrachyov** [comment]
Exactly what I meant. The first one [above]  looks great. So, could you make some instances of this one in different sizes [resolution of picture] and then I'll add it to the main page?

**Comment by newfinal100** [comment]
Yeah sure! I'll upload them all on Google Drive and share the link with you here, is that okay? :)

**Comment by EgorOrachyov** [comment]
Of course, this is one of the best ways !)

**Comment by newfinal100** [comment]
https://drive.google.com/drive/folders/1jcOCXdziYpou3YlTTqBMGPRSl-MiEpe5?usp=sharing

If there are some other formats or sizes than the I one have provided here, feel free to tell me and I'll upload those too! Also if you need anything else let me know :)

**Comment by EgorOrachyov** [comment]
Upload new logo. In my opinion, it looks awesome! 
If you have new ideas about engine/appearance, contact me too. It would be great!
